plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

packageExtensions:
  "graphql-compose-mongoose@*":
    dependencies:
      mongodb: "*"

yarnPath: .yarn/releases/yarn-berry.cjs
nodeLinker: "pnp"
enableInlineHunks: true